# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cgpa.ui'
#
# Created: Sat Sep 24 18:57:04 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName(_fromUtf8("window"))
        window.resize(557, 440)
        self.centralframe = QtGui.QWidget(window)
        self.centralframe.setObjectName(_fromUtf8("centralframe"))
        self.gridLayout = QtGui.QGridLayout(self.centralframe)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralframe)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.box = QtGui.QGroupBox(self.frame)
        self.box.setGeometry(QtCore.QRect(20, 20, 510, 390))
        self.box.setStyleSheet(_fromUtf8("selection-background-color: rgb(0, 85, 255);"))
        self.box.setTitle(_fromUtf8(""))
        self.box.setObjectName(_fromUtf8("box"))
        self.label = QtGui.QLabel(self.box)
        self.label.setGeometry(QtCore.QRect(1, 26, 81, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.box)
        self.label_2.setGeometry(QtCore.QRect(86, 22, 51, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.box)
        self.label_3.setGeometry(QtCore.QRect(140, 26, 81, 17))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.box)
        self.line.setGeometry(QtCore.QRect(71, 20, 20, 350))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.box)
        self.line_2.setGeometry(QtCore.QRect(131, 20, 20, 350))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.box)
        self.line_3.setGeometry(QtCore.QRect(0, 40, 241, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.box)
        self.line_4.setGeometry(QtCore.QRect(-3, 10, 241, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.grade1 = QtGui.QComboBox(self.box)
        self.grade1.setGeometry(QtCore.QRect(150, 60, 71, 27))
        self.grade1.setStyleSheet(_fromUtf8("selection-background-color: rgb(85, 85, 255);\n"
"selection-color: rgb(255, 255, 255);"))
        self.grade1.setObjectName(_fromUtf8("grade1"))
        self.grade1.addItem(_fromUtf8(""))
        self.grade1.addItem(_fromUtf8(""))
        self.grade1.addItem(_fromUtf8(""))
        self.grade1.addItem(_fromUtf8(""))
        self.grade1.addItem(_fromUtf8(""))
        self.grade1.addItem(_fromUtf8(""))
        self.grade1.addItem(_fromUtf8(""))
        self.line_5 = QtGui.QFrame(self.box)
        self.line_5.setGeometry(QtCore.QRect(0, 360, 241, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gpa_button = QtGui.QToolButton(self.box)
        self.gpa_button.setGeometry(QtCore.QRect(260, 160, 101, 25))
        self.gpa_button.setObjectName(_fromUtf8("gpa_button"))
        self.cgpa_button = QtGui.QToolButton(self.box)
        self.cgpa_button.setGeometry(QtCore.QRect(300, 210, 151, 25))
        self.cgpa_button.setObjectName(_fromUtf8("cgpa_button"))
        self.label_6 = QtGui.QLabel(self.box)
        self.label_6.setGeometry(QtCore.QRect(400, 160, 41, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.grade2 = QtGui.QComboBox(self.box)
        self.grade2.setGeometry(QtCore.QRect(150, 90, 71, 27))
        self.grade2.setObjectName(_fromUtf8("grade2"))
        self.grade2.addItem(_fromUtf8(""))
        self.grade2.addItem(_fromUtf8(""))
        self.grade2.addItem(_fromUtf8(""))
        self.grade2.addItem(_fromUtf8(""))
        self.grade2.addItem(_fromUtf8(""))
        self.grade2.addItem(_fromUtf8(""))
        self.grade2.addItem(_fromUtf8(""))
        self.grade3 = QtGui.QComboBox(self.box)
        self.grade3.setGeometry(QtCore.QRect(150, 120, 71, 27))
        self.grade3.setObjectName(_fromUtf8("grade3"))
        self.grade3.addItem(_fromUtf8(""))
        self.grade3.addItem(_fromUtf8(""))
        self.grade3.addItem(_fromUtf8(""))
        self.grade3.addItem(_fromUtf8(""))
        self.grade3.addItem(_fromUtf8(""))
        self.grade3.addItem(_fromUtf8(""))
        self.grade3.addItem(_fromUtf8(""))
        self.grade4 = QtGui.QComboBox(self.box)
        self.grade4.setGeometry(QtCore.QRect(150, 150, 71, 27))
        self.grade4.setObjectName(_fromUtf8("grade4"))
        self.grade4.addItem(_fromUtf8(""))
        self.grade4.addItem(_fromUtf8(""))
        self.grade4.addItem(_fromUtf8(""))
        self.grade4.addItem(_fromUtf8(""))
        self.grade4.addItem(_fromUtf8(""))
        self.grade4.addItem(_fromUtf8(""))
        self.grade4.addItem(_fromUtf8(""))
        self.grade5 = QtGui.QComboBox(self.box)
        self.grade5.setGeometry(QtCore.QRect(150, 180, 71, 27))
        self.grade5.setObjectName(_fromUtf8("grade5"))
        self.grade5.addItem(_fromUtf8(""))
        self.grade5.addItem(_fromUtf8(""))
        self.grade5.addItem(_fromUtf8(""))
        self.grade5.addItem(_fromUtf8(""))
        self.grade5.addItem(_fromUtf8(""))
        self.grade5.addItem(_fromUtf8(""))
        self.grade5.addItem(_fromUtf8(""))
        self.grade6 = QtGui.QComboBox(self.box)
        self.grade6.setGeometry(QtCore.QRect(150, 210, 71, 27))
        self.grade6.setObjectName(_fromUtf8("grade6"))
        self.grade6.addItem(_fromUtf8(""))
        self.grade6.addItem(_fromUtf8(""))
        self.grade6.addItem(_fromUtf8(""))
        self.grade6.addItem(_fromUtf8(""))
        self.grade6.addItem(_fromUtf8(""))
        self.grade6.addItem(_fromUtf8(""))
        self.grade6.addItem(_fromUtf8(""))
        self.grade7 = QtGui.QComboBox(self.box)
        self.grade7.setGeometry(QtCore.QRect(150, 240, 71, 27))
        self.grade7.setObjectName(_fromUtf8("grade7"))
        self.grade7.addItem(_fromUtf8(""))
        self.grade7.addItem(_fromUtf8(""))
        self.grade7.addItem(_fromUtf8(""))
        self.grade7.addItem(_fromUtf8(""))
        self.grade7.addItem(_fromUtf8(""))
        self.grade7.addItem(_fromUtf8(""))
        self.grade7.addItem(_fromUtf8(""))
        self.grade8 = QtGui.QComboBox(self.box)
        self.grade8.setGeometry(QtCore.QRect(150, 270, 71, 27))
        self.grade8.setObjectName(_fromUtf8("grade8"))
        self.grade8.addItem(_fromUtf8(""))
        self.grade8.addItem(_fromUtf8(""))
        self.grade8.addItem(_fromUtf8(""))
        self.grade8.addItem(_fromUtf8(""))
        self.grade8.addItem(_fromUtf8(""))
        self.grade8.addItem(_fromUtf8(""))
        self.grade8.addItem(_fromUtf8(""))
        self.gpa = QtGui.QLabel(self.box)
        self.gpa.setGeometry(QtCore.QRect(440, 160, 81, 17))
        self.gpa.setText(_fromUtf8(""))
        self.gpa.setObjectName(_fromUtf8("gpa"))
        self.crthsem = QtGui.QLabel(self.box)
        self.crthsem.setGeometry(QtCore.QRect(440, 120, 67, 17))
        self.crthsem.setText(_fromUtf8(""))
        self.crthsem.setObjectName(_fromUtf8("crthsem"))
        self.editgrades = QtGui.QToolButton(self.box)
        self.editgrades.setGeometry(QtCore.QRect(350, 350, 151, 25))
        self.editgrades.setObjectName(_fromUtf8("editgrades"))
        self.sem = QtGui.QComboBox(self.box)
        self.sem.setGeometry(QtCore.QRect(410, 280, 41, 21))
        self.sem.setObjectName(_fromUtf8("sem"))
        self.credit1 = QtGui.QLabel(self.box)
        self.credit1.setGeometry(QtCore.QRect(100, 64, 40, 17))
        self.credit1.setObjectName(_fromUtf8("credit1"))
        self.credit3 = QtGui.QLabel(self.box)
        self.credit3.setGeometry(QtCore.QRect(100, 124, 40, 17))
        self.credit3.setObjectName(_fromUtf8("credit3"))
        self.credit5 = QtGui.QLabel(self.box)
        self.credit5.setGeometry(QtCore.QRect(100, 184, 40, 17))
        self.credit5.setObjectName(_fromUtf8("credit5"))
        self.credit4 = QtGui.QLabel(self.box)
        self.credit4.setGeometry(QtCore.QRect(100, 154, 40, 17))
        self.credit4.setObjectName(_fromUtf8("credit4"))
        self.credit7 = QtGui.QLabel(self.box)
        self.credit7.setGeometry(QtCore.QRect(100, 244, 40, 17))
        self.credit7.setObjectName(_fromUtf8("credit7"))
        self.credit6 = QtGui.QLabel(self.box)
        self.credit6.setGeometry(QtCore.QRect(100, 214, 40, 17))
        self.credit6.setObjectName(_fromUtf8("credit6"))
        self.credit8 = QtGui.QLabel(self.box)
        self.credit8.setGeometry(QtCore.QRect(100, 274, 40, 17))
        self.credit8.setObjectName(_fromUtf8("credit8"))
        self.credit2 = QtGui.QLabel(self.box)
        self.credit2.setGeometry(QtCore.QRect(100, 94, 40, 17))
        self.credit2.setObjectName(_fromUtf8("credit2"))
        self.sub2 = QtGui.QLabel(self.box)
        self.sub2.setGeometry(QtCore.QRect(10, 95, 67, 17))
        self.sub2.setObjectName(_fromUtf8("sub2"))
        self.sub5 = QtGui.QLabel(self.box)
        self.sub5.setGeometry(QtCore.QRect(10, 185, 67, 17))
        self.sub5.setObjectName(_fromUtf8("sub5"))
        self.sub8 = QtGui.QLabel(self.box)
        self.sub8.setGeometry(QtCore.QRect(10, 275, 67, 17))
        self.sub8.setObjectName(_fromUtf8("sub8"))
        self.sub3 = QtGui.QLabel(self.box)
        self.sub3.setGeometry(QtCore.QRect(10, 125, 67, 17))
        self.sub3.setObjectName(_fromUtf8("sub3"))
        self.sub4 = QtGui.QLabel(self.box)
        self.sub4.setGeometry(QtCore.QRect(10, 155, 67, 17))
        self.sub4.setObjectName(_fromUtf8("sub4"))
        self.sub1 = QtGui.QLabel(self.box)
        self.sub1.setGeometry(QtCore.QRect(10, 65, 67, 17))
        self.sub1.setObjectName(_fromUtf8("sub1"))
        self.sub6 = QtGui.QLabel(self.box)
        self.sub6.setGeometry(QtCore.QRect(10, 215, 67, 17))
        self.sub6.setObjectName(_fromUtf8("sub6"))
        self.sub7 = QtGui.QLabel(self.box)
        self.sub7.setGeometry(QtCore.QRect(10, 245, 67, 17))
        self.sub7.setObjectName(_fromUtf8("sub7"))
        self.credit10 = QtGui.QLabel(self.box)
        self.credit10.setGeometry(QtCore.QRect(100, 335, 40, 17))
        self.credit10.setObjectName(_fromUtf8("credit10"))
        self.grade10 = QtGui.QComboBox(self.box)
        self.grade10.setGeometry(QtCore.QRect(150, 331, 71, 27))
        self.grade10.setObjectName(_fromUtf8("grade10"))
        self.grade10.addItem(_fromUtf8(""))
        self.grade10.addItem(_fromUtf8(""))
        self.grade10.addItem(_fromUtf8(""))
        self.grade10.addItem(_fromUtf8(""))
        self.grade10.addItem(_fromUtf8(""))
        self.grade10.addItem(_fromUtf8(""))
        self.grade10.addItem(_fromUtf8(""))
        self.sub10 = QtGui.QLabel(self.box)
        self.sub10.setGeometry(QtCore.QRect(10, 336, 67, 17))
        self.sub10.setObjectName(_fromUtf8("sub10"))
        self.credit9 = QtGui.QLabel(self.box)
        self.credit9.setGeometry(QtCore.QRect(100, 305, 40, 17))
        self.credit9.setObjectName(_fromUtf8("credit9"))
        self.grade9 = QtGui.QComboBox(self.box)
        self.grade9.setGeometry(QtCore.QRect(150, 301, 71, 27))
        self.grade9.setObjectName(_fromUtf8("grade9"))
        self.grade9.addItem(_fromUtf8(""))
        self.grade9.addItem(_fromUtf8(""))
        self.grade9.addItem(_fromUtf8(""))
        self.grade9.addItem(_fromUtf8(""))
        self.grade9.addItem(_fromUtf8(""))
        self.grade9.addItem(_fromUtf8(""))
        self.grade9.addItem(_fromUtf8(""))
        self.sub9 = QtGui.QLabel(self.box)
        self.sub9.setGeometry(QtCore.QRect(10, 306, 67, 17))
        self.sub9.setObjectName(_fromUtf8("sub9"))
        self.line_6 = QtGui.QFrame(self.box)
        self.line_6.setGeometry(QtCore.QRect(-9, 20, 20, 350))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.box)
        self.line_7.setGeometry(QtCore.QRect(230, 20, 20, 350))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.save = QtGui.QToolButton(self.box)
        self.save.setGeometry(QtCore.QRect(340, 70, 50, 25))
        self.save.setObjectName(_fromUtf8("save"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(280, 140, 181, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        window.setCentralWidget(self.centralframe)
        self.actionCalculate = QtGui.QAction(window)
        self.actionCalculate.setObjectName(_fromUtf8("actionCalculate"))

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)
        window.setTabOrder(self.grade1, self.grade2)
        window.setTabOrder(self.grade2, self.grade3)
        window.setTabOrder(self.grade3, self.grade4)
        window.setTabOrder(self.grade4, self.grade5)
        window.setTabOrder(self.grade5, self.grade6)
        window.setTabOrder(self.grade6, self.grade7)
        window.setTabOrder(self.grade7, self.grade8)
        window.setTabOrder(self.grade8, self.gpa_button)
        window.setTabOrder(self.gpa_button, self.cgpa_button)

    def retranslateUi(self, window):
        window.setWindowTitle(QtGui.QApplication.translate("window", "GPA / CGPA Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("window", "Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("window", "Cr.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("window", "Grade", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade1.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.gpa_button.setText(QtGui.QApplication.translate("window", "Calculate GPA", None, QtGui.QApplication.UnicodeUTF8))
        self.cgpa_button.setText(QtGui.QApplication.translate("window", "Show CGPA analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("window", "GPA :", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade2.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade3.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade4.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade5.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade6.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade7.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade8.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.editgrades.setText(QtGui.QApplication.translate("window", "Edit grading system", None, QtGui.QApplication.UnicodeUTF8))
        self.credit1.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit3.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit5.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit4.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit7.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit6.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit8.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit2.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub2.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub5.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub8.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub3.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub4.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub1.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub6.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sub7.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit10.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade10.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.sub10.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.credit9.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(0, QtGui.QApplication.translate("window", "S = 10", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(1, QtGui.QApplication.translate("window", "A = 9", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(2, QtGui.QApplication.translate("window", "B = 8", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(3, QtGui.QApplication.translate("window", "C = 7", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(4, QtGui.QApplication.translate("window", "D = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(5, QtGui.QApplication.translate("window", "E = 4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade9.setItemText(6, QtGui.QApplication.translate("window", "U = 2", None, QtGui.QApplication.UnicodeUTF8))
        self.sub9.setText(QtGui.QApplication.translate("window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("window", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("window", "Credits for this semester:", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculate.setText(QtGui.QApplication.translate("window", "Calculate", None, QtGui.QApplication.UnicodeUTF8))

