# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editsem.ui'
#
# Created: Tue Oct 11 22:06:21 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName(_fromUtf8("window"))
        window.resize(395, 430)
        self.centralwidget = QtGui.QWidget(window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 39, 92, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 71, 97, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(9, 103, 56, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(9, 133, 71, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.subjectcode = QtGui.QLineEdit(self.centralwidget)
        self.subjectcode.setGeometry(QtCore.QRect(112, 34, 91, 27))
        self.subjectcode.setObjectName(_fromUtf8("subjectcode"))
        self.subjectname = QtGui.QLineEdit(self.centralwidget)
        self.subjectname.setGeometry(QtCore.QRect(112, 67, 271, 27))
        self.subjectname.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.subjectname.setObjectName(_fromUtf8("subjectname"))
        self.add = QtGui.QToolButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(71, 220, 71, 25))
        self.add.setObjectName(_fromUtf8("add"))
        self.toolButton_2 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(242, 220, 81, 25))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.label_5.setStyleSheet(_fromUtf8("font: 75 12pt \"Ubuntu\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 12, 311, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 111, 20))
        self.label_6.setStyleSheet(_fromUtf8("font: 75 12pt \"Ubuntu\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(117, 250, 296, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.subdelete = QtGui.QComboBox(self.centralwidget)
        self.subdelete.setGeometry(QtCore.QRect(128, 309, 101, 27))
        self.subdelete.setObjectName(_fromUtf8("subdelete"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(12, 312, 92, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.toolButton_3 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(240, 360, 81, 25))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.delete_2 = QtGui.QToolButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(70, 360, 71, 25))
        self.delete_2.setObjectName(_fromUtf8("delete_2"))
        self.semadd = QtGui.QSpinBox(self.centralwidget)
        self.semadd.setGeometry(QtCore.QRect(110, 130, 59, 27))
        self.semadd.setObjectName(_fromUtf8("semadd"))
        self.semdelete = QtGui.QComboBox(self.centralwidget)
        self.semdelete.setGeometry(QtCore.QRect(128, 277, 61, 27))
        self.semdelete.setObjectName(_fromUtf8("semdelete"))
        self.semdelete.addItem(_fromUtf8(""))
        self.semdelete.setItemText(0, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 280, 92, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(9, 163, 151, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.classes = QtGui.QSpinBox(self.centralwidget)
        self.classes.setGeometry(QtCore.QRect(180, 160, 59, 27))
        self.classes.setObjectName(_fromUtf8("classes"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(9, 193, 161, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.attendance = QtGui.QDoubleSpinBox(self.centralwidget)
        self.attendance.setGeometry(QtCore.QRect(180, 190, 62, 27))
        self.attendance.setObjectName(_fromUtf8("attendance"))
        self.credits = QtGui.QSpinBox(self.centralwidget)
        self.credits.setGeometry(QtCore.QRect(110, 100, 59, 27))
        self.credits.setObjectName(_fromUtf8("credits"))
        window.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        window.setStatusBar(self.statusbar)
        self.label.setBuddy(self.subjectcode)
        self.label_2.setBuddy(self.subjectname)
        self.label_7.setBuddy(self.subjectcode)
        self.label_8.setBuddy(self.subjectcode)

        self.retranslateUi(window)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), window.close)
        QtCore.QObject.connect(self.toolButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), window.close)
        QtCore.QMetaObject.connectSlotsByName(window)
        window.setTabOrder(self.subjectcode, self.subjectname)
        window.setTabOrder(self.subjectname, self.credits)
        window.setTabOrder(self.credits, self.semadd)
        window.setTabOrder(self.semadd, self.classes)
        window.setTabOrder(self.classes, self.attendance)
        window.setTabOrder(self.attendance, self.add)
        window.setTabOrder(self.add, self.toolButton_2)
        window.setTabOrder(self.toolButton_2, self.semdelete)
        window.setTabOrder(self.semdelete, self.subdelete)
        window.setTabOrder(self.subdelete, self.delete_2)
        window.setTabOrder(self.delete_2, self.toolButton_3)

    def retranslateUi(self, window):
        window.setWindowTitle(QtGui.QApplication.translate("window", "Add / Delete Subjects", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("window", "Course Code :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("window", "Course Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("window", "Credits :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("window", "Semester :", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("window", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("window", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("window", "Add Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("window", "Delete Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("window", "Course Code :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("window", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_2.setText(QtGui.QApplication.translate("window", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("window", "Semester :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("window", "Total No. of Classes :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("window", "% attendance required :", None, QtGui.QApplication.UnicodeUTF8))

